# Generated by Django 5.1.7 on 2025-03-28 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Szak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szakNev', models.CharField(max_length=100)),
                ('tamogatott', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Szakok',
            },
        ),
        migrations.CreateModel(
            name='Felvetelizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('szulEv', models.IntegerField()),
                ('pontszam', models.IntegerField()),
                ('kep', models.ImageField(null=True, upload_to='images/')),
                ('szakId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felviadmin.szak')),
            ],
            options={
                'verbose_name_plural': 'Felvételizők',
            },
        ),
    ]
